service: sample-flask-lambda-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ca-central-1
  iamRoleStatements:
  - Effect: Allow
    Action: "s3:*"
    Resource: "*"

functions:
  app:
    handler: wsgi_handler.handler
    events: 
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**